# Site settings
title: 철원사람 rudyannnn
url: "https://rudyannnn.github.io"
baseurl: ""
description: >
    철원사람 블로그

# My information
email: rudyannn@gmail.com
author: 철원사람 rudyannnn
profile: 철원사람
twitter_username: ru983k
github_username: rudyannnn
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: rudyannnn
  shortname: rudyannnn
utterances:
  repo: rudyannnn/rudyannnn.github.io
  issue-term: pathname
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/rudyannnn/rudyannnn.github.io/blame/master/_wiki"
edit: "https://github.com/rudyannnn/rudyannnn.github.io/edit/master/_wiki"
issue: "https://github.com/rudyannnn/rudyannnn.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
